In [1]:
import numpy as np

In [3]:
arr_2d = np.arange(50).reshape(5,10)

In [4]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [5]:
arr_2d[2:4,2:4]

array([[22, 23],
       [32, 33]])

In [12]:
arr_2d[arr_2d > 32].reshape(1,17)

array([[33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49]])